x-common: &common
  build:
    args:
      - NODE_VER=20.13.1
    context: .
    dockerfile: Dockerfile
  tty: true
  volumes:
    - .:/home/node/app
    - ./node_modules:/home/node/app_node_modules
  environment:
    - CHOKIDAR_USEPOLLING

services:
  web:
    <<: *common
    ports:
      - 3000:3000
    command: npm run dev
  storybook:
    <<: *common
    ports:
      - 6006:6006
    command: npm run storybook
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  node_modules:
  postgres_data:
